import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./Footer/page";
import Navbar from "../components/Navbar/Navbar";
import BadgeWhatsapp from "../components/badgeWhatsapp/BadgeWhatsapp";
import Chatbot from "../components/Chatbot/Chatbot";
import { AuthProvider } from "../contexts/authContext";
import { UserProvider } from "../contexts/UserContext";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Peludopolis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GoogleOAuthProvider clientId="428954429923-bicutvc9ci34rlq7c1pdv7kivd3n87c7.apps.googleusercontent.com">
            <AuthProvider>
              <UserProvider>
                <div className="flex flex-col min-h-screen">
                  <Navbar />
                  <main className="flex-grow">{children}</main>
                  <Footer />
                </div>
                <BadgeWhatsapp />
                <Chatbot />
              </UserProvider>
            </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
